### ISSUE TITLE
Use the application

### ISSUE THREAD

**Issue by mcoulont** [grossvater/jcl-parser#3]
Hi. I've successfully built jcl-parser. But how to use it?

**Comment by grossvater** [comment]
Sorry, I haven't watched the repo for a while. You could take a look [here](https://github.com/grossvater/jcl-parser/blob/6c942f246ca664c007584c30dfb8fd653f7dc923/modules/org.grossvater.jcl.parser.test/src/main/java/org/grossvater/jcl/parser/AntlrUtils.java#L53) for an example for parser instantiation.
